env:
  IMAGE_NODE: elrond-testnet-node
  REGISTRY_HOSTNAME: miiu

name: Build Docker image

#on:
#  release:
#    types: [published]

on: [push]


jobs:
  build:
    strategy:
      matrix:
        runs-on: [ubuntu-latest]
    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: "Build image"
        run: |
          cd ${GITHUB_WORKSPACE} && make see-files
          # TAG_VERSION=${{ steps.get_version.outputs.VERSION }}
          TAG_VERSION=v1.1.1
          docker build -t "${REGISTRY_HOSTNAME}/${IMAGE_NODE}:${TAG_VERSION}" -f ./../docker/Dockerfile .


